Name:           ros-indigo-oxford-gps-eth
Version:        0.0.6
Release:        0%{?dist}
Summary:        ROS oxford_gps_eth package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/oxford_gps_eth
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-roslaunch
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-tf
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-roslaunch
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-tf

%description
Ethernet interface to OxTS GPS receivers (NCOM packet structure)

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Mar 26 2018 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 0.0.6-0
- Autogenerated by Bloom

* Thu Aug 10 2017 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 0.0.5-0
- Autogenerated by Bloom

* Mon Apr 11 2016 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 0.0.4-0
- Autogenerated by Bloom

* Mon Dec 21 2015 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 0.0.3-0
- Autogenerated by Bloom

* Mon Dec 14 2015 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 0.0.2-0
- Autogenerated by Bloom

* Thu Dec 10 2015 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 0.0.1-0
- Autogenerated by Bloom

